# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE CATALOG IF NOT EXISTS RETAIL_CATALOG;
# MAGIC
# MAGIC USE CATALOG RETAIL_CATALOG;
# MAGIC
# MAGIC CREATE SCHEMA IF NOT EXISTS BRONZE;
# MAGIC CREATE SCHEMA IF NOT EXISTS SILVER;
# MAGIC CREATE SCHEMA IF NOT EXISTS GOLD